# Used when running Spring app locally
services:
  db:
    image: 'postgres:17'
    container_name: shortener-db
    restart: unless-stopped
    shm_size: 128mb
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DB_USER:-devuser}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-devpass}
      POSTGRES_DB: ${DB_NAME:-shortener_dev}
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - pg-data-local:/var/lib/postgresql/data/pgdata
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DB_USER:-devuser} -d ${DB_NAME:-shortener_dev}" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s
    networks:
      - shortener-backend

volumes:
  pg-data-local:
    driver: local

networks:
  shortener-backend:
    driver: bridge